# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#f
name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Download ANTLR
      working-directory: ./minijavacompiler/src/main/scala/parseTreeFiles
      run: sudo apt-get install antlr4 && sudo apt install rsync
    - name: Build ANTLR Files
      working-directory: ./minijavacompiler/src/main/scala/parseTreeFiles/grammarOutput
      run: antlr4 miniJava.g4 -visitor && javac -classpath /usr/share/java/antlr4-runtime.jar miniJava*.java
    - name: LS grammarOutput
      working-directory: ./minijavacompiler/src/main/scala/parseTreeFiles/grammarOutput
      run: ls
    - name: Recompile SBT
      working-directory: ./minijavacompiler
      run: sbt clean clean-cache clean-lib clean-plugins && sbt compile
    - name: Run tests
      working-directory: ./minijavacompiler
      run: sbt test
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
      with:
        working-directory: ./minijavacompiler
